import { useEffect,useState } from 'react';
import { Link,useParams } from 'react-router-dom';
import { Agreement,AgreementDocument,agreementDocumentUrl,deleteAgreementDocument,generateAgreement,getAgreement,getAgreementDocuments,submitAgreement,uploadAgreementDocument } from '../services/api';
const TYPES=[['IDENTITY_PROOF','Identity proof'],['ADDRESS_PROOF','Address proof'],['OWNERSHIP_PROOF','Ownership / authorization proof'],['PHOTOGRAPH','Photograph'],['OTHER','Other']];
export default function AgreementDetails(){const{id}=useParams();const[item,setItem]=useState<Agreement|null>(null);const[docs,setDocs]=useState<AgreementDocument[]>([]);const[type,setType]=useState(TYPES[0][0]);const[busy,setBusy]=useState(false);const[error,setError]=useState('');const[generated,setGenerated]=useState(false);
 useEffect(()=>{if(!id)return;Promise.all([getAgreement(id),getAgreementDocuments(id)]).then(([a,d])=>{setItem(a);setDocs(d)}).catch(e=>setError(e instanceof Error?e.message:'Unable to load agreement'))},[id]);
 async function submit(){if(!id)return;setBusy(true);try{setItem(await submitAgreement(id))}catch(e){setError(e instanceof Error?e.message:'Unable to submit agreement')}finally{setBusy(false)}}
 async function upload(e:React.ChangeEvent<HTMLInputElement>){if(!id||!e.target.files?.[0])return;const file=e.target.files[0];setBusy(true);setError('');try{const doc=await uploadAgreementDocument(id,file,type);setDocs(d=>[doc,...d])}catch(e){setError(e instanceof Error?e.message:'Unable to upload document')}finally{setBusy(false);e.target.value=''}}
 async function remove(docId:string){if(!id||!confirm('Delete this document?'))return;setBusy(true);try{await deleteAgreementDocument(id,docId);setDocs(d=>d.filter(x=>x.id!==docId))}catch(e){setError(e instanceof Error?e.message:'Unable to delete document')}finally{setBusy(false)}}
 async function generate(){if(!id)return;setBusy(true);try{await generateAgreement(id);setGenerated(true);const d=await getAgreementDocuments(id);setDocs(d)}catch(e){setError(e instanceof Error?e.message:'Unable to generate draft')}finally{setBusy(false)}}
 if(error&&!item)return <main className="page"><Link to="/agreements">← Agreements</Link><div className="error" role="alert">{error}</div></main>;if(!item)return <main className="page"><p>Loading agreement…</p></main>;
 return <main className="page"><Link to="/agreements">← Agreements</Link><div className="dashboard-head"><div><span className="kicker">Agreement</span><h1>{item.property?.title||'Rental agreement'}</h1><p>{item.property?.areaName}, {item.property?.city}</p></div><span className="status-badge">{item.status.replace('_',' ')}</span></div>{error&&<div className="error" role="alert">{error}</div>}
 <section className="dashboard-panel"><div className="agreement-timeline"><div className="timeline-step done"><strong>Details submitted</strong><span>Agreement record created</span></div><div className={`timeline-step ${item.status!=='DRAFT'?'done':'current'}`}><strong>Review</strong><span>Both parties should review the terms</span></div><div className="timeline-step"><strong>Formalities</strong><span>Complete applicable execution requirements</span></div><div className="timeline-step"><strong>Completed</strong><span>Only after required formalities are completed</span></div></div>
 <div className="form-grid"><div><strong>Monthly rent</strong><p>₹{Number(item.rent).toLocaleString('en-IN')}</p></div><div><strong>Security deposit</strong><p>{item.deposit==null?'Not specified':`₹${Number(item.deposit).toLocaleString('en-IN')}`}</p></div><div><strong>Start</strong><p>{new Date(item.startDate).toLocaleDateString('en-IN')}</p></div><div><strong>End</strong><p>{new Date(item.endDate).toLocaleDateString('en-IN')}</p></div><div><strong>Rent due</strong><p>{item.rentDueDate}th of each month</p></div><div><strong>Notice</strong><p>{item.noticePeriod||'Not specified'}</p></div></div>
 <div className="terms"><h2>Agreed terms</h2><p><strong>Maintenance:</strong> {item.maintenanceResponsibility||'Not specified'}</p><p><strong>Utilities:</strong> {item.utilities||'Not specified'}</p><p><strong>Pets:</strong> {item.pets||'Not specified'}</p><p><strong>Subletting:</strong> {item.subletting||'Not specified'}</p><p><strong>Additional terms:</strong> {item.additionalTerms||'None'}</p></div>
 <section className="terms"><h2>Documents</h2><p>Private documents are accessible only to authorized agreement participants.</p><div className="form-grid"><label>Document type<select value={type} onChange={e=>setType(e.target.value)}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><label>Choose PDF, JPEG, or PNG<input type="file" accept="application/pdf,image/jpeg,image/png" onChange={upload} disabled={busy}/><small>Maximum 5 MB.</small></label></div>{docs.length===0?<p>No documents uploaded yet.</p>:<ul>{docs.map(doc=><li key={doc.id}><strong>{TYPES.find(x=>x[0]===doc.documentType)?.[1]||doc.documentType}</strong> — {doc.status} <a href={agreementDocumentUrl(id!,doc.id)} target="_blank" rel="noreferrer">View</a> <button type="button" onClick={()=>remove(doc.id)} disabled={busy}>Delete</button></li>)}</ul>}</section>
 <div className="form-actions">{item.status==='DRAFT'&&<button className="button" onClick={submit} disabled={busy}>{busy?'Working…':'Submit for review'}</button>}{item.status!=='DRAFT'&&<button className="button" onClick={generate} disabled={busy}>{busy?'Generating…':'Generate draft PDF'}</button>}{generated&&<span role="status">Draft generated and stored privately.</span>}</div><p className="legal-note">A generated or submitted agreement is not represented as legally executed, registered, or stamped by this platform. Applicable legal and formal requirements must be completed separately.</p></section></main>;
}
