import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Agreement, getAgreement, submitAgreement } from '../services/api';

export default function AgreementDetails() {
  const { id } = useParams(); const [item, setItem] = useState<Agreement | null>(null); const [error,setError]=useState(''); const [busy,setBusy]=useState(false);
  useEffect(()=>{ if(id) getAgreement(id).then(setItem).catch(e=>setError(e instanceof Error?e.message:'Unable to load agreement')); },[id]);
  async function submit(){ if(!id)return; setBusy(true); try{setItem(await submitAgreement(id));}catch(e){setError(e instanceof Error?e.message:'Unable to submit agreement')}finally{setBusy(false)} }
  if(error&&!item)return <main className="page"><Link to="/agreements">← Agreements</Link><div className="error" role="alert">{error}</div></main>;
  if(!item)return <main className="page"><p>Loading agreement…</p></main>;
  return <main className="page"><Link to="/agreements">← Agreements</Link><div className="dashboard-head"><div><span className="kicker">Agreement</span><h1>{item.property?.title || 'Rental agreement'}</h1><p>{item.property?.areaName}, {item.property?.city}</p></div><span className="status-badge">{item.status.replaceAll('_',' ')}</span></div>{error&&<div className="error" role="alert">{error}</div>}<section className="dashboard-panel"><div className="agreement-timeline"><div className="timeline-step done"><strong>Details submitted</strong><span>Agreement record created</span></div><div className={`timeline-step ${item.status !== 'DRAFT' ? 'done' : 'current'}`}><strong>Review</strong><span>Both parties should review the terms</span></div><div className="timeline-step"><strong>Formalities</strong><span>Complete applicable execution requirements</span></div><div className="timeline-step"><strong>Completed</strong><span>Only after the required process is actually completed</span></div></div><div className="form-grid"><div><strong>Monthly rent</strong><p>₹{Number(item.rent).toLocaleString('en-IN')}</p></div><div><strong>Security deposit</strong><p>{item.deposit == null ? 'Not specified' : `₹${Number(item.deposit).toLocaleString('en-IN')}`}</p></div><div><strong>Start</strong><p>{new Date(item.startDate).toLocaleDateString('en-IN')}</p></div><div><strong>End</strong><p>{new Date(item.endDate).toLocaleDateString('en-IN')}</p></div><div><strong>Rent due</strong><p>{item.rentDueDate}th of each month</p></div><div><strong>Notice</strong><p>{item.noticePeriod || 'Not specified'}</p></div></div><div className="terms"><h2>Agreed terms</h2><p><strong>Maintenance:</strong> {item.maintenanceResponsibility || 'Not specified'}</p><p><strong>Utilities:</strong> {item.utilities || 'Not specified'}</p><p><strong>Pets:</strong> {item.pets || 'Not specified'}</p><p><strong>Subletting:</strong> {item.subletting || 'Not specified'}</p><p><strong>Additional terms:</strong> {item.additionalTerms || 'None'}</p></div>{item.status==='DRAFT'&&<button className="button" onClick={submit} disabled={busy}>{busy?'Submitting…':'Submit for review'}</button>}<p className="legal-note">A generated or submitted agreement is not represented as legally executed, registered, or stamped by this platform. Applicable legal and formal requirements must be completed separately.</p></section></main>;
}
