import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { createAgreement } from '../services/api';

export default function NewAgreement() {
  const navigate = useNavigate();
  const [form, setForm] = useState({ propertyId:'', ownerId:'', tenantId:'', rent:'', deposit:'', startDate:'', endDate:'', rentDueDate:'1', noticePeriod:'30 days', maintenanceResponsibility:'', utilities:'', pets:'Not specified', subletting:'Not permitted', additionalTerms:'' });
  const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const set = (key: string, value: string) => setForm(prev => ({...prev, [key]: value}));
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); setSaving(true); try { const agreement = await createAgreement({...form, rent:Number(form.rent), deposit: form.deposit ? Number(form.deposit) : undefined, rentDueDate:Number(form.rentDueDate)} as never); navigate(`/agreements/${agreement.id}`); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to create agreement'); } finally { setSaving(false); } }
  return <main className="page"><Link to="/agreements">← Agreements</Link><div className="dashboard-head"><div><span className="kicker">Step 1</span><h1>Start a rental agreement</h1><p>Enter the agreed terms carefully. The other party must be a verified participant in the selected property relationship.</p></div></div>{error && <div className="error" role="alert">{error}</div>}<form className="form-card" onSubmit={submit}><div className="form-grid"><label>Property ID<input required value={form.propertyId} onChange={e=>set('propertyId',e.target.value)} /></label><label>Owner ID<input required value={form.ownerId} onChange={e=>set('ownerId',e.target.value)} /></label><label>Tenant ID<input required value={form.tenantId} onChange={e=>set('tenantId',e.target.value)} /></label><label>Monthly rent<input required type="number" min="1" value={form.rent} onChange={e=>set('rent',e.target.value)} /></label><label>Security deposit<input type="number" min="0" value={form.deposit} onChange={e=>set('deposit',e.target.value)} /></label><label>Rent due day<input required type="number" min="1" max="31" value={form.rentDueDate} onChange={e=>set('rentDueDate',e.target.value)} /></label><label>Start date<input required type="date" value={form.startDate} onChange={e=>set('startDate',e.target.value)} /></label><label>End date<input required type="date" value={form.endDate} onChange={e=>set('endDate',e.target.value)} /></label></div><label>Notice period<textarea value={form.noticePeriod} onChange={e=>set('noticePeriod',e.target.value)} /></label><label>Maintenance responsibility<textarea value={form.maintenanceResponsibility} onChange={e=>set('maintenanceResponsibility',e.target.value)} /></label><label>Utilities<textarea value={form.utilities} onChange={e=>set('utilities',e.target.value)} /></label><label>Pets<textarea value={form.pets} onChange={e=>set('pets',e.target.value)} /></label><label>Subletting<textarea value={form.subletting} onChange={e=>set('subletting',e.target.value)} /></label><label>Additional terms<textarea maxLength={5000} value={form.additionalTerms} onChange={e=>set('additionalTerms',e.target.value)} /></label><button className="button" disabled={saving}>{saving ? 'Saving…' : 'Create draft agreement'}</button></form></main>;
}
